# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chalet < Formula
  desc "Connect Claude to your Chalet"
  homepage "https://github.com/chalet-do/chalet-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.2.0/chalet_0.2.0_darwin_amd64.tar.gz"
      sha256 "8dc5d583e79ecd3180a2d9e391255195a53228d9117b37a0526613563732f8b5"

      define_method(:install) do
        bin.install "chalet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.2.0/chalet_0.2.0_darwin_arm64.tar.gz"
      sha256 "8680861d87411d458674046228607c01c8eb5ee11d4ab73162044123bd7947c1"

      define_method(:install) do
        bin.install "chalet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.2.0/chalet_0.2.0_linux_amd64.tar.gz"
      sha256 "3c710e96fca71cb87afde7eaae758fcadcfd0e4329255293e879d57899783b63"
      define_method(:install) do
        bin.install "chalet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.2.0/chalet_0.2.0_linux_arm64.tar.gz"
      sha256 "ecce1730d9e07148ccbfed7e65be62848851832b7d320583eee79a7c1733d712"
      define_method(:install) do
        bin.install "chalet"
      end
    end
  end
end
