# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chalet < Formula
  desc "Connect Claude to your Chalet"
  homepage "https://github.com/chalet-do/chalet-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.1.2/chalet_0.1.2_darwin_amd64.tar.gz"
      sha256 "e72597fe393de3a5262b3d5d33eef33437578ff9fbaef1a1e826de7bf6a4b3d7"

      define_method(:install) do
        bin.install "chalet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.1.2/chalet_0.1.2_darwin_arm64.tar.gz"
      sha256 "bf753faea40f3554a8b3a4781f6ce6913c333518d7f782fc9a48d0fe857b69b5"

      define_method(:install) do
        bin.install "chalet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.1.2/chalet_0.1.2_linux_amd64.tar.gz"
      sha256 "7b21e4688df7414e6fcdbd49c07f4a77c9e39d7b7a208f915a6376d11ebccfd6"
      define_method(:install) do
        bin.install "chalet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chalet-do/chalet-cli/releases/download/v0.1.2/chalet_0.1.2_linux_arm64.tar.gz"
      sha256 "e8dff5fd9c9d4efe63f2c934afd66296cefdefc7ca42c9986e2947ab26fb6fdd"
      define_method(:install) do
        bin.install "chalet"
      end
    end
  end
end
